spring.application.name=urlshortener

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortenerdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
